'use client'

export async function generatePayrollPDF(report, summary, teamName, startDate, weekEndStr) {
  // Dynamically load jsPDF + autotable
  if (!window.jspdf) {
    await loadScript('https://cdnjs.cloudflare.com/ajax/libs/jspdf/2.5.1/jspdf.umd.min.js')
    await loadScript('https://cdnjs.cloudflare.com/ajax/libs/jspdf-autotable/3.8.2/jspdf.plugin.autotable.min.js')
  }

  const { jsPDF } = window.jspdf
  const doc = new jsPDF()

  const PINK = [255, 31, 125]
  const DARK = [15, 23, 42]
  const GRAY = [100, 116, 139]
  const LIGHT_PINK = [255, 240, 247]
  const pageWidth = doc.internal.pageSize.getWidth()

  // ── Pink header bar ──
  doc.setFillColor(...PINK)
  doc.rect(0, 0, pageWidth, 28, 'F')

  doc.setTextColor(255, 255, 255)
  doc.setFontSize(20)
  doc.setFont('helvetica', 'bold')
  doc.text('Shiftly', 14, 14)

  doc.setFontSize(10)
  doc.setFont('helvetica', 'normal')
  doc.text('Payroll Report', 14, 22)

  doc.setFontSize(9)
  doc.text(teamName, pageWidth - 14, 14, { align: 'right' })
  doc.text(`${formatDateGB(startDate)} – ${formatDateGB(weekEndStr)}`, pageWidth - 14, 22, { align: 'right' })

  // ── Summary boxes ──
  let y = 36
  const boxWidth = (pageWidth - 28 - 12) / 4
  const summaryItems = [
    { label: 'Total Hours', value: `${summary.total_hours || 0}h` },
    { label: 'Regular Hours', value: `${summary.total_regular_hours || 0}h` },
    { label: 'Overtime Hours', value: `${summary.total_overtime_hours || 0}h` },
    { label: 'Labour Cost', value: `£${(summary.total_cost || 0).toFixed(2)}` }
  ]

  summaryItems.forEach((item, i) => {
    const x = 14 + i * (boxWidth + 4)
    const isAccent = i === 3

    doc.setFillColor(...(isAccent ? LIGHT_PINK : [248, 250, 252]))
    doc.roundedRect(x, y, boxWidth, 20, 2, 2, 'F')

    doc.setFontSize(7)
    doc.setTextColor(...GRAY)
    doc.setFont('helvetica', 'normal')
    doc.text(item.label, x + 4, y + 7)

    doc.setFontSize(14)
    doc.setTextColor(...(isAccent ? PINK : DARK))
    doc.setFont('helvetica', 'bold')
    doc.text(item.value, x + 4, y + 16)
  })

  y += 28

  // ── Staff table ──
  doc.setFontSize(11)
  doc.setTextColor(...DARK)
  doc.setFont('helvetica', 'bold')
  doc.text('Staff Breakdown', 14, y)
  y += 4

  const tableData = report
    .filter(s => s.scheduled_hours > 0 || s.hourly_rate > 0)
    .map(s => {
      let status = 'Under'
      if (s.contracted_hours > 0) {
        if (s.scheduled_hours > s.contracted_hours) status = 'Over'
        else if (s.scheduled_hours === s.contracted_hours) status = 'Met'
      }
      return [
        s.name, s.role,
        `${s.contracted_hours}h`, `${s.scheduled_hours}h`,
        `${s.regular_hours}h`,
        s.overtime_hours > 0 ? `${s.overtime_hours}h` : '-',
        s.hourly_rate > 0 ? `£${s.hourly_rate.toFixed(2)}` : '-',
        s.hourly_rate > 0 ? `£${s.total_cost.toFixed(2)}` : '-',
        status
      ]
    })

  doc.autoTable({
    startY: y,
    head: [['Name', 'Role', 'Contract', 'Scheduled', 'Regular', 'Overtime', 'Rate', 'Cost', 'Status']],
    body: tableData,
    theme: 'grid',
    headStyles: {
      fillColor: PINK,
      textColor: [255, 255, 255],
      fontSize: 7,
      fontStyle: 'bold',
      cellPadding: 3
    },
    bodyStyles: {
      fontSize: 7,
      textColor: DARK,
      cellPadding: 2.5
    },
    alternateRowStyles: {
      fillColor: [248, 250, 252]
    },
    columnStyles: {
      0: { fontStyle: 'bold', cellWidth: 28 },
      1: { cellWidth: 22 },
      2: { halign: 'center', cellWidth: 18 },
      3: { halign: 'center', cellWidth: 20 },
      4: { halign: 'center', cellWidth: 18 },
      5: { halign: 'center', cellWidth: 18 },
      6: { halign: 'right', cellWidth: 16 },
      7: { halign: 'right', cellWidth: 18 },
      8: { halign: 'center', cellWidth: 16 }
    },
    didParseCell: (data) => {
      if (data.section === 'body' && data.column.index === 8) {
        const val = data.cell.raw
        if (val === 'Over') {
          data.cell.styles.textColor = [220, 38, 38]
          data.cell.styles.fontStyle = 'bold'
        } else if (val === 'Met') {
          data.cell.styles.textColor = [22, 163, 74]
          data.cell.styles.fontStyle = 'bold'
        } else {
          data.cell.styles.textColor = [217, 119, 6]
        }
      }
    },
    margin: { left: 14, right: 14 }
  })

  // ── Totals row ──
  const finalY = doc.lastAutoTable.finalY + 4
  doc.setFontSize(8)
  doc.setFont('helvetica', 'bold')
  doc.setTextColor(...DARK)
  doc.text(`Total: ${summary.total_hours || 0}h scheduled • £${(summary.total_cost || 0).toFixed(2)} labour cost • ${summary.staff_count || 0} staff`, 14, finalY)

  // ── Footer on all pages ──
  const totalPages = doc.internal.getNumberOfPages()
  for (let i = 1; i <= totalPages; i++) {
    doc.setPage(i)
    const pageHeight = doc.internal.pageSize.getHeight()
    doc.setFontSize(7)
    doc.setTextColor(...GRAY)
    doc.setFont('helvetica', 'normal')
    doc.text(
      `Generated by Shiftly on ${new Date().toLocaleDateString('en-GB')} • Page ${i} of ${totalPages}`,
      pageWidth / 2, pageHeight - 8,
      { align: 'center' }
    )
  }

  const filename = `payroll-${teamName.toLowerCase().replace(/\s+/g, '-')}-${startDate}.pdf`
  doc.save(filename)
}

function loadScript(src) {
  return new Promise((resolve, reject) => {
    if (document.querySelector(`script[src="${src}"]`)) {
      resolve()
      return
    }
    const script = document.createElement('script')
    script.src = src
    script.onload = resolve
    script.onerror = reject
    document.head.appendChild(script)
  })
}

function formatDateGB(dateStr) {
  const d = new Date(dateStr)
  return d.toLocaleDateString('en-GB', { day: 'numeric', month: 'short', year: 'numeric' })
}